site_name: UCL-GOSH Data Interchange for Sensors Classifications
nav:
    - Back to Portfolio Website: https://comp0016-team6.github.io/
    - Home: index.md
    - Getting Started: getting_started.md
    - User Manual: 
        - Admin: admin.md
        - Clinicians: clinicians.md
        - Patients: patients.md
theme: material